### ISSUE TITLE
Change peer dependency to parcel instead of parcel-bundler

### ISSUE THREAD

**Issue by brielov** [mischnic/parcel-plugin-sw-cache#26]
Parcel is published as `parcel` on npm too. It would be nice to suppress warnings like `has unmet peer dependency` by changing the peer dependency from parcel-bundler to just parcel.

**Comment by mischnic** [comment]
The problem is that there would always be a warning if you used the other package (`parcel` vs `parcel-bundler`). Given that `parcel-bundler` is more common, it makes more sense to keep it as is.
(The whole situation with Parcel having a different name isn't ideal for plugins , even more if you need to require something from Parcel itself).
